return {
  { 'ellisonleao/gruvbox.nvim' },
  { 'water-sucks/darkrose.nvim' },
  { 'catppuccin/nvim', name = 'catppuccin' },
  { 'rose-pine/neovim', name = 'rose-pine' },
  { 'folke/tokyonight.nvim' },
  { 'miikanissi/modus-themes.nvim' },
  { 'mofiqul/dracula.nvim' },
  { 'phha/zenburn.nvim' },
  { 'nyoom-engineering/oxocarbon.nvim' },
  { 'marko-cerovac/material.nvim' },
  { 'projekt0n/github-nvim-theme' },
  { 'edeneast/nightfox.nvim' },
  { 'olimorris/onedarkpro.nvim' },
  { 'maxmx03/solarized.nvim' },
  { 'gbprod/nord.nvim' },
  { 'rebelot/kanagawa.nvim' },
  { 'mhartington/oceanic-next' },
  { 'sainnhe/everforest' },
  { 'zedddie16/pastelpink' },
}
